opcache.enable=1
opcache.validate_timestamps=0
opcache.max_accelerated_files=20000
opcache.memory_consumption=128
memory_limit=256M
; JSON API without uploads.
file_uploads=Off
upload_max_filesize=1M
post_max_size=64K
max_input_time=10
max_execution_time=15
expose_php=Off
display_errors=Off
log_errors=On
